FROM rockylinux:9.6

RUN dnf -y upgrade \
  && dnf install -y epel-release dnf-plugins-core \
  && dnf config-manager --enable crb \
  && dnf install -y \
    iputils \
    jq \
    libtiff \
    munge \
    net-tools \
    openssh-server \
    python3 \
    python3-devel \
    python3-pip \
    sudo \
    which \
    zip unzip \
  && dnf clean all

ENV CRYOSPARC_ROOT_DIR=/app
RUN mkdir -p ${CRYOSPARC_ROOT_DIR}
WORKDIR ${CRYOSPARC_ROOT_DIR}

ARG CRYOSPARC_LICENSE_ID
ENV CRYOSPARC_LICENSE_ID=${CRYOSPARC_LICENSE_ID}

# download
RUN curl -L https://get.cryosparc.com/download/master-latest/${CRYOSPARC_LICENSE_ID} -o cryosparc_master.tar.gz
RUN tar -xzf cryosparc_master.tar.gz

ENV CRYOSPARC_MASTER_DIR=${CRYOSPARC_ROOT_DIR}/cryosparc_master
WORKDIR ${CRYOSPARC_MASTER_DIR}

# install cryosparc with non-privileged user
ENV USER=cryosparc
# allow any user to start service
RUN sed -i '/^echo "# Other" >> config.sh$/a echo \"export CRYOSPARC_FORCE_USER=true\" >> config.sh' ./install.sh
# make sure cryosparc uses explicit container name not the one generated by build
RUN sed -i '/^echo "# Other" >> config.sh$/a echo \"export CRYOSPARC_HOSTNAME_CHECK=localhost\" >> config.sh' ./install.sh
ENV CRYOSPARC_MASTER_HOSTNAME=localhost

RUN ./install.sh \
    --yes \
    --license $CRYOSPARC_LICENSE_ID \
    --hostname "localhost"

COPY start_cryosparc.sh /start_cryosparc.sh
RUN chmod 0755 /start_cryosparc.sh

EXPOSE 39000 39001 39002 39003 39004 39006

ENV PATH=$PATH:${CRYOSPARC_MASTER_DIR}/bin

# make socket file deterministic
RUN root_dir_hash=$(echo -n $CRYOSPARC_ROOT_DIR | md5sum | awk '{print $1}')
RUN export CRYOSPARC_SUPERVISOR_SOCK_FILE=/tmp/cryosparc-supervisor-${root_dir_hash}.sock

ENTRYPOINT ["/start_cryosparc.sh"]
